---
- name: Update apt cache on all Debian/Ubuntu servers
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
